#!/bin/bash

OPTIONS_SPEC="\
git first-merge [-- <log-args>...]

Show the SHA-1 of the first merge commit.

Extra options for the git log command can be passed (e.g. a different
revision/revision range could be passed).
--
"

SUBDIRECTORY_OK=yes

. "$(git --exec-path)/git-sh-setup"

if [[ "$1" == "--" ]]; then
    shift
fi

exec git log -n1 --merges --format=%H "$@"
